import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import "@testing-library/jest-dom/vitest";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { TerminalPanel } from "./TerminalPanel";
import type { VpsRecord } from "../../../lib/api";

const sockets: MockSocket[] = [];
const terminals: Array<{ cols: number; rows: number; emit: (data: string) => void; focus: ReturnType<typeof vi.fn>; dispose: ReturnType<typeof vi.fn> }> = [];
const observers: Array<{ callback: () => void; disconnect: ReturnType<typeof vi.fn> }> = [];
const fits: Array<{ fit: ReturnType<typeof vi.fn>; dispose: ReturnType<typeof vi.fn> }> = [];
class MockSocket {
  static OPEN = 1;
  readyState = 0;
  sent: string[] = [];
  onopen?: () => void; onmessage?: (event: { data: string }) => void;
  onerror?: () => void; onclose?: () => void;
  constructor(public url: string) { sockets.push(this); }
  send(value: string) { this.sent.push(value); }
  close() { this.readyState = 3; this.onclose?.(); }
  open() { this.readyState = 1; this.onopen?.(); }
  message(value: unknown) { this.onmessage?.({ data: JSON.stringify(value) }); }
}

vi.mock("@xterm/xterm", () => ({ Terminal: class { cols = 80; rows = 24; handler?: (data: string) => void; focus = vi.fn(); dispose = vi.fn(); constructor() { terminals.push(this); } onData = vi.fn((handler: (data: string) => void) => { this.handler = handler; return { dispose: vi.fn(() => { this.handler = undefined; }) }; }); emit(data: string) { this.handler?.(data); } open = vi.fn(); loadAddon = vi.fn(); write = vi.fn(); } }));
vi.mock("@xterm/addon-fit", () => ({ FitAddon: class { fit = vi.fn(); dispose = vi.fn(); constructor() { fits.push(this); } } }));

const vps = { id: "vps-1", name: "demo", displayName: "Demo", host: "example.test", port: 22, username: "admin", createdAt: "", updatedAt: "" } as VpsRecord;
const rootVps = { ...vps, username: "root" };

beforeEach(() => { sockets.length = 0; terminals.length = 0; observers.length = 0; fits.length = 0; vi.stubGlobal("WebSocket", MockSocket); vi.stubGlobal("ResizeObserver", class { disconnect = vi.fn(); observe = vi.fn(); constructor(public callback: () => void) { observers.push(this); } }); });
afterEach(() => { cleanup(); vi.useRealTimers(); });

describe("TerminalPanel", () => {
  it("does not open a socket when disabled", () => { render(<TerminalPanel vps={vps} enabled={false} />); expect(screen.getByText("Web terminal is disabled for this environment.")).toBeInTheDocument(); expect(sockets).toHaveLength(0); });
  it("returns to disconnected when enabled without auto-connecting", () => { const { rerender } = render(<TerminalPanel vps={vps} enabled={false} />); expect(screen.getByText("Web terminal is disabled for this environment.")).toBeInTheDocument(); rerender(<TerminalPanel vps={vps} enabled />); expect(screen.getByRole("button", { name: /^Connect$/i })).toBeInTheDocument(); expect(screen.queryByText("Web terminal is disabled for this environment.")).not.toBeInTheDocument(); expect(sockets).toHaveLength(0); });
  it("explicitly connects with the route VPS and bounded dimensions", () => { render(<TerminalPanel vps={vps} />); fireEvent.click(screen.getByRole("button", { name: /^Connect$/i })); expect(sockets[0].url).toContain("/api/vps/vps-1/terminal"); sockets[0].open(); expect(JSON.parse(sockets[0].sent[0])).toMatchObject({ type: "open", version: 1, vpsId: "vps-1", cols: 80, rows: 24 }); });
  it("handles ready and output without rendering output in React", async () => { render(<TerminalPanel vps={vps} />); fireEvent.click(screen.getByRole("button", { name: /^Connect$/i })); sockets[0].open(); sockets[0].message({ type: "ready", terminalSessionId: "s1", startedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 60000).toISOString() }); sockets[0].message({ type: "output", data: "secret output" }); await waitFor(() => expect(screen.getAllByText("Connected").length).toBeGreaterThan(0)); expect(screen.queryByText("secret output")).not.toBeInTheDocument(); });
  it("shows safe server errors and cleans up", async () => { const { unmount } = render(<TerminalPanel vps={vps} />); fireEvent.click(screen.getByRole("button", { name: /^Connect$/i })); sockets[0].open(); sockets[0].message({ type: "error", code: "INTERNAL_ERROR", message: "private stack trace", retryable: false }); await waitFor(() => expect(screen.getByText(/could not be opened/i)).toBeInTheDocument()); unmount(); expect(sockets[0].readyState).toBe(3); });
  it("preserves a closed state and reconnect opens a new socket", async () => { render(<TerminalPanel vps={vps} />); fireEvent.click(screen.getByRole("button", { name: /^Connect$/i })); sockets[0].open(); sockets[0].message({ type: "ready", terminalSessionId: "s1", startedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 60000).toISOString() }); sockets[0].close(); await waitFor(() => expect(screen.getByText(/closed unexpectedly/i)).toBeInTheDocument()); fireEvent.click(screen.getByRole("button", { name: /^Reconnect$/i })); expect(sockets).toHaveLength(2); expect(sockets[1].url).toContain("/api/vps/vps-1/terminal"); });
  it("shows the persistent root warning", () => { render(<TerminalPanel vps={rootVps} />); expect(screen.getByText(/Root shell/)).toBeInTheDocument(); expect(screen.getByText("ROOT")).toBeInTheDocument(); });
  it("expires and stops the socket after ready expiry", async () => { vi.useFakeTimers(); render(<TerminalPanel vps={vps} />); fireEvent.click(screen.getByRole("button", { name: /^Connect$/i })); sockets[0].open(); sockets[0].message({ type: "ready", terminalSessionId: "s1", startedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 1000).toISOString() }); await vi.advanceTimersByTimeAsync(1001); expect(screen.getAllByText(/session expired/i).length).toBeGreaterThan(0); expect(sockets[0].readyState).toBe(3); });
  it("sends debounced bounded resize and disposes on unmount", () => { vi.useFakeTimers(); const { unmount } = render(<TerminalPanel vps={vps} />); fireEvent.click(screen.getByRole("button", { name: /^Connect$/i })); sockets[0].open(); unmount(); expect(sockets[0].readyState).toBe(3); });
  it("requires explicit confirmation before disconnecting", async () => { render(<TerminalPanel vps={vps} />); fireEvent.click(screen.getByRole("button", { name: /^Connect$/i })); sockets[0].open(); sockets[0].message({ type: "ready", terminalSessionId: "s1", startedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 60000).toISOString() }); await screen.findByText("Close active SSH session?", {}, { timeout: 1 }).catch(() => undefined); fireEvent.click(screen.getByRole("button", { name: /disconnect/i })); expect(screen.getByRole("alertdialog")).toHaveTextContent("Close active SSH session?"); expect(sockets[0].readyState).toBe(1); fireEvent.click(screen.getByRole("button", { name: "Keep session open" })); expect(sockets[0].readyState).toBe(1); fireEvent.click(screen.getByRole("button", { name: /disconnect/i })); fireEvent.click(screen.getByRole("button", { name: "Disconnect and leave" })); expect(sockets[0].readyState).toBe(3); });
  it("sends single-line input directly but confirms multiline paste without displaying or persisting it", async () => { render(<TerminalPanel vps={vps} />); fireEvent.click(screen.getByRole("button", { name: /^Connect$/i })); sockets[0].open(); terminals[0].emit("echo safe"); expect(JSON.parse(sockets[0].sent.at(-1)!)).toEqual({ type: "input", data: "echo safe" }); const terminal = screen.getByRole("application"); const clipboardData = { getData: () => "first secret\nsecond secret" }; fireEvent.paste(terminal, { clipboardData }); expect(screen.getByRole("alertdialog")).toHaveTextContent("Paste multiple lines?"); expect(screen.queryByText(/first secret/)).not.toBeInTheDocument(); const count = sockets[0].sent.length; fireEvent.click(screen.getByRole("button", { name: "Cancel paste" })); expect(sockets[0].sent).toHaveLength(count); fireEvent.paste(terminal, { clipboardData }); fireEvent.click(screen.getByRole("button", { name: "Paste into terminal" })); expect(JSON.parse(sockets[0].sent.at(-1)!)).toEqual({ type: "input", data: "first secret\nsecond secret" }); });
  it("debounces resize, bounds dimensions, focuses on ready, and cleans resources", async () => { vi.useFakeTimers(); const { unmount } = render(<TerminalPanel vps={vps} />); fireEvent.click(screen.getByRole("button", { name: /^Connect$/i })); sockets[0].open(); terminals[0].cols = 900; terminals[0].rows = 0; observers[0].callback(); observers[0].callback(); expect(sockets[0].sent).toHaveLength(1); await vi.advanceTimersByTimeAsync(119); expect(sockets[0].sent).toHaveLength(1); await vi.advanceTimersByTimeAsync(1); expect(JSON.parse(sockets[0].sent.at(-1)!)).toEqual({ type: "resize", cols: 500, rows: 1 }); sockets[0].message({ type: "ready", terminalSessionId: "s1", startedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 60000).toISOString() }); expect(terminals[0].focus).toHaveBeenCalledOnce(); unmount(); expect(observers[0].disconnect).toHaveBeenCalledOnce(); expect(terminals[0].dispose).toHaveBeenCalledOnce(); });
  it("fully replaces connection resources across repeated reconnects and ignores stale work", async () => { vi.useFakeTimers(); const { unmount } = render(<TerminalPanel vps={vps} />); const terminalElement = screen.getByRole("application"); const removeSpy = vi.spyOn(terminalElement, "removeEventListener"); fireEvent.click(screen.getByRole("button", { name: /^Connect$/i })); const first = sockets[0]; act(() => first.open()); const staleMessage = first.onmessage!; act(() => first.message({ type: "error", message: "timeout" })); fireEvent.click(screen.getByRole("button", { name: /^Reconnect$/i })); expect(observers[0].disconnect).toHaveBeenCalledOnce(); expect(terminals[0].dispose).toHaveBeenCalledOnce(); expect(fits[0].dispose).toHaveBeenCalledOnce(); expect(removeSpy).toHaveBeenCalledWith("paste", expect.any(Function), true); const firstCount = first.sent.length; terminals[0].emit("stale input"); expect(first.sent).toHaveLength(firstCount); const second = sockets[1]; act(() => second.open()); act(() => staleMessage({ data: JSON.stringify({ type: "error", message: "authentication stale" }) })); expect(screen.queryByText("authentication stale")).not.toBeInTheDocument(); observers[0].callback(); observers[1].callback(); observers[1].callback(); await vi.advanceTimersByTimeAsync(120); expect(second.sent.filter((value) => JSON.parse(value).type === "resize")).toHaveLength(1); act(() => second.message({ type: "error", message: "timeout" })); fireEvent.click(screen.getByRole("button", { name: /^Reconnect$/i })); expect(observers[1].disconnect).toHaveBeenCalledOnce(); expect(terminals[1].dispose).toHaveBeenCalledOnce(); expect(fits[1].dispose).toHaveBeenCalledOnce(); unmount(); expect(observers[2].disconnect).toHaveBeenCalledOnce(); expect(terminals[2].dispose).toHaveBeenCalledOnce(); expect(fits[2].dispose).toHaveBeenCalledOnce(); expect(observers.every((item) => item.disconnect.mock.calls.length === 1)).toBe(true); expect(terminals.every((item) => item.dispose.mock.calls.length === 1)).toBe(true); expect(fits.every((item) => item.dispose.mock.calls.length === 1)).toBe(true); });
});
