import type { FormEvent, ReactNode } from "react";
import { Activity, ArrowDownRight, ArrowUpRight, Clock3, Cpu, HardDrive, KeyRound, MapPin, MemoryStick, Network, Server, ServerCog, ShieldCheck, Tag, TerminalSquare, Trash2, type LucideIcon } from "lucide-react";
import { Alert } from "../ui/alert";
import { Badge } from "../ui/badge";
import { Button } from "../ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../ui/card";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import { chipVariant, formatDate, freshnessLabel, serverStatusLabel } from "../../lib/dashboard-formatters";
import type { DashboardOverview, VpsRecord } from "../../lib/api";

export function DemoBanner({ overview }: { overview: DashboardOverview }) {
  if (!overview.banner) return null;
  return <Alert className="mb-4 rounded-2xl border-0 bg-white/75 text-primary shadow-sm ring-1 ring-primary/10">{overview.banner}</Alert>;
}

export function OverviewPanel({ overview }: { overview: DashboardOverview }) {
  const avg = (key: "cpu" | "memory" | "disk") => overview.metrics.length ? Math.round(overview.metrics.reduce((sum, metric) => sum + metric[key], 0) / overview.metrics.length) : 0;
  const warningTotal = overview.summary.warningServers + overview.summary.unreachableServers;

  function findTrend(unit?: string) {
    const metric = overview.metrics.find((m) => m.trend?.unit === unit);
    if (metric?.trend) return metric.trend;
    const anyTrend = overview.metrics.find((m) => m.trend);
    return anyTrend?.trend ?? null;
  }

  const cpuTrend = findTrend("cpu");
  const memTrend = findTrend("memory");
  const diskTrend = findTrend("disk");
  const netTrend = findTrend("network") || findTrend();

  return <div className="min-w-0 space-y-4 overflow-visible"><section className="grid min-w-0 gap-3 xl:grid-cols-3" aria-label="Operations overview"><HeroStat tone="healthy" label="Fleet health" title={`${overview.summary.healthyServers} healthy`} detail={`${overview.summary.totalServers} total · ${warningTotal} need attention`} icon={Server} /><HeroStat tone="work" label="Key & job status" title={`${overview.summary.runningJobs} running`} detail="Provisioning and verification queue" icon={KeyRound} /><HeroStat tone="load" label="Resource balance" title={`${avg("cpu")}% CPU`} detail={`${avg("memory")}% RAM · ${avg("disk")}% disk`} icon={Activity} /></section><DemoBanner overview={overview} /><section className="grid min-w-0 gap-4 md:grid-cols-2 2xl:grid-cols-4"><TrendCard label="CPU load" value={`${avg("cpu")}%`} detail={cpuTrend ? `${cpuTrend.range} · min ${cpuTrend.min}% max ${cpuTrend.max}%` : `${overview.metrics.length} samples`} icon={Cpu} tone="cyan" trend={cpuTrend} /><TrendCard label="Memory pressure" value={`${avg("memory")}%`} detail={memTrend ? `${memTrend.range} · min ${memTrend.min}% max ${memTrend.max}%` : `${Math.max(0, 100 - avg("memory"))}% headroom`} icon={MemoryStick} tone="violet" trend={memTrend} /><TrendCard label="Disk usage" value={`${avg("disk")}%`} detail={diskTrend ? `${diskTrend.range} · min ${diskTrend.min}% max ${diskTrend.max}%` : `across ${overview.metrics.length} servers`} icon={HardDrive} tone="amber" trend={diskTrend} /><TrendCard label="Network in/out" value={`${Math.max(12, avg("cpu") * 3)} Mbps`} detail={`${Math.max(4, avg("memory"))} Mbps out`} icon={Network} tone="slate" trend={netTrend} /></section><div className="grid min-w-0 max-w-full gap-4 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]"><AuditPanel events={overview.auditEvents.slice(0, 5)} compact /><JobsPanel jobs={overview.jobs.slice(0, 5)} compact /></div></div>;
}

function HeroStat({ tone, label, title, detail, icon: Icon }: { tone: "healthy" | "work" | "load"; label: string; title: string; detail: string; icon: LucideIcon }) {
  const tones = { healthy: "border-emerald-500/30 bg-slate-950 text-white before:bg-emerald-400 text-emerald-200", work: "border-amber-500/30 bg-slate-900 text-white before:bg-amber-400 text-amber-200", load: "border-indigo-500/30 bg-slate-900 text-white before:bg-indigo-400 text-indigo-200" };
  return <article className={`${tones[tone]} before:absolute before:inset-x-0 before:top-0 before:h-1 relative min-h-28 min-w-0 overflow-hidden rounded-[1.15rem] border p-4 pt-5 shadow-sm shadow-slate-950/10 sm:min-h-32`}><div className="absolute -right-10 -top-12 h-24 w-24 rounded-full bg-current/10 blur-2xl" /><div className="relative flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-xs font-black uppercase tracking-[0.16em] text-slate-400">{label}</p><h2 className="mt-1 truncate font-display text-2xl text-white sm:text-[1.7rem]">{title}</h2><p className="mt-1 truncate text-[15px] font-semibold leading-6 text-slate-300">{detail}</p></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/10 bg-white/10 text-current"><Icon size={20} /></span></div></article>;
}

function TrendCard({ label, value, detail, icon: Icon, trend, tone }: { label: string; value: string; detail: string; icon: LucideIcon; trend?: { points: number[]; min: number; max: number; threshold: number; range?: string; unit?: string } | null; tone: "cyan" | "violet" | "amber" | "slate" }) {
  const stroke = { cyan: "#06b6d4", violet: "#6366f1", amber: "#d97706", slate: "#334155" }[tone];
  const points = trend?.points ?? [25, 35, 30, 45, 40, 50];
  const normalized = points.map((point) => Math.min(92, Math.max(8, point)));
  const polyline = normalized.map((point, index) => `${index * 20},${54 - point / 2}`).join(" ");
  const max = trend?.max ?? Math.max(...normalized);
  const min = trend?.min ?? Math.min(...normalized);
  const threshold = trend?.threshold ?? 80;
  const range = trend?.range ?? "60m";
  const isHot = max > 78;
  return <Card className={`min-w-0 overflow-hidden border-slate-200 bg-white shadow-sm ${isHot ? "ring-2 ring-orange-200" : ""}`}><CardContent className="p-4"><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-xs font-black uppercase tracking-[0.14em] text-slate-500">{label}</p><strong className="mt-1 block truncate text-2xl font-black text-slate-950">{value}</strong><p className="mt-1 truncate text-[15px] font-semibold leading-6 text-slate-500">{detail}</p></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-slate-200 bg-slate-50 text-slate-700"><Icon size={18} /></span></div><div className="mt-3 flex items-center justify-between gap-2 text-xs font-black uppercase tracking-[0.08em] text-slate-500"><span>Last {range}</span><span className={isHot ? "text-orange-600" : "text-slate-500"}>threshold {threshold}%</span></div><svg className="mt-2 h-14 w-full overflow-visible" viewBox="0 0 100 56" preserveAspectRatio="none" aria-hidden="true"><line x1="0" y1="14" x2="100" y2="14" stroke={isHot ? "#f97316" : "#cbd5e1"} strokeDasharray="4 4" /><polyline points={polyline} fill="none" stroke={isHot ? "#f97316" : stroke} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /><line x1="0" y1="44" x2="100" y2="44" stroke="#e2e8f0" strokeDasharray="4 4" /></svg><div className="mt-1 flex items-center justify-between text-sm font-bold leading-6 text-slate-500"><span>min {min}%</span><span>max {max}%</span></div></CardContent></Card>;
}

type ServersPanelProps = {
  records: VpsRecord[];
  visibleRecords: VpsRecord[];
  statusMessage: ReactNode;
  serverSearch: string;
  statusFilter: string;
  busy: boolean;
  provisionPasswords: Record<string, string>;
  createForm: { name: string; host: string; port: string; username: string; password: string };
  onSearchChange: (value: string) => void;
  onStatusFilterChange: (value: string) => void;
  onCreateFormChange: (value: ServersPanelProps["createForm"]) => void;
  onCreate: (event: FormEvent<HTMLFormElement>) => void;
  onPasswordChange: (id: string, value: string) => void;
  onProvision: (vps: VpsRecord, event: FormEvent<HTMLFormElement>) => void;
  onVerify: (vps: VpsRecord) => void;
  onDelete: (vps: VpsRecord) => void;
};

export function ServersPanel(props: ServersPanelProps) {
  return <div className="grid min-w-0 max-w-full gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(0,360px)]"><section className="min-w-0 space-y-4"><Card className="min-w-0 overflow-hidden border-0"><CardHeader className="min-w-0"><CardTitle className="truncate">Servers</CardTitle><CardDescription>Search, filter, provision keys, verify access.</CardDescription></CardHeader><CardContent className="min-w-0 space-y-4"><div className="grid min-w-0 gap-3 md:grid-cols-[minmax(0,1fr)_180px]"><Input aria-label="Tìm server" placeholder="Search name, host, provider, tag..." value={props.serverSearch} onChange={(event) => props.onSearchChange(event.target.value)} /><select aria-label="Lọc trạng thái" className="h-11 min-w-0 w-full rounded-2xl border-0 bg-secondary px-3 text-sm font-semibold text-primary outline-none ring-1 ring-primary/10 focus:ring-4 focus:ring-ring" value={props.statusFilter} onChange={(event) => props.onStatusFilterChange(event.target.value)}><option value="all">All states</option><option value="healthy">Healthy</option><option value="warning">Warning</option><option value="unreachable">Down</option><option value="ready">Key ready</option><option value="pending">Needs password</option></select></div>{props.statusMessage}{props.records.length === 0 ? <EmptyState>Chưa có VPS nào. Thêm server đầu tiên ở form bên cạnh.</EmptyState> : props.visibleRecords.length === 0 ? <EmptyState>Không tìm thấy VPS phù hợp bộ lọc.</EmptyState> : <div className="grid min-w-0 gap-3 2xl:grid-cols-2">{props.visibleRecords.map((vps) => <ServerCard key={vps.id} vps={vps} busy={props.busy} password={props.provisionPasswords[vps.id] || ""} onPasswordChange={props.onPasswordChange} onProvision={props.onProvision} onVerify={props.onVerify} onDelete={props.onDelete} />)}</div>}</CardContent></Card></section><CreateServerCard {...props} /></div>;
}

function CreateServerCard({ createForm, busy, onCreate, onCreateFormChange }: ServersPanelProps) {
  return <Card className="h-fit min-w-0 overflow-hidden border-0 bg-[#f6f2ff]"><CardHeader className="min-w-0"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-white text-primary shadow-sm"><Server size={22} /></div><p className="truncate text-xs font-black uppercase tracking-[0.18em] text-accent">Add server</p><CardTitle className="truncate">New VPS</CardTitle><CardDescription>Password is optional and never stored.</CardDescription></CardHeader><CardContent><form onSubmit={onCreate} autoComplete="off" className="grid min-w-0 gap-3"><Label>Tên<Input required maxLength={120} placeholder="prod-sgp-01" value={createForm.name} onChange={(event) => onCreateFormChange({ ...createForm, name: event.target.value })} /></Label><Label>Host / IP<Input required maxLength={255} placeholder="203.0.113.20" value={createForm.host} onChange={(event) => onCreateFormChange({ ...createForm, host: event.target.value })} /></Label><div className="grid min-w-0 gap-3 sm:grid-cols-2"><Label>Port<Input required type="number" min={1} max={65535} value={createForm.port} onChange={(event) => onCreateFormChange({ ...createForm, port: event.target.value })} /></Label><Label>Username<Input required maxLength={64} placeholder="root" value={createForm.username} onChange={(event) => onCreateFormChange({ ...createForm, username: event.target.value })} /></Label></div><Label>Password tùy chọn<Input type="password" maxLength={4096} autoComplete="new-password" placeholder="One-time key install" value={createForm.password} onChange={(event) => onCreateFormChange({ ...createForm, password: event.target.value })} /></Label><Button type="submit" disabled={busy} className="min-w-0 rounded-2xl"><Server size={18} /><span className="truncate">Tạo VPS</span></Button></form></CardContent></Card>;
}

function ServerCard({ vps, busy, password, onPasswordChange, onProvision, onVerify, onDelete }: { vps: VpsRecord; busy: boolean; password: string; onPasswordChange: (id: string, value: string) => void; onProvision: ServersPanelProps["onProvision"]; onVerify: ServersPanelProps["onVerify"]; onDelete: ServersPanelProps["onDelete"] }) {
  const isReady = Boolean(vps.keyProvisionedAt);
  return <article className="min-w-0 rounded-lg border border-border bg-card/80 p-4 shadow-panel"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="font-black tracking-tight">{vps.name}</h3><p className="break-all text-sm text-muted-foreground">{vps.username}@{vps.host}:{vps.port}</p></div><div className="flex flex-wrap gap-2"><Badge variant={chipVariant(vps.status)}>{serverStatusLabel(vps.status)}</Badge><Badge variant={isReady ? "ready" : "pending"}>{isReady ? "Key ready" : "Needs password"}</Badge></div></div><div className="mt-3 grid gap-2 text-sm text-muted-foreground sm:grid-cols-2"><span className="flex items-center gap-2"><ServerCog size={15} />{vps.provider || "Provider not set"}</span><span className="flex items-center gap-2"><MapPin size={15} />{vps.region || "Region not set"}</span><span className="flex items-center gap-2"><Clock3 size={15} />Seen: {formatDate(vps.lastSeenAt)}</span><span className="flex items-center gap-2"><Clock3 size={15} />Key: {isReady ? formatDate(vps.keyProvisionedAt) : "not provisioned"}</span></div>{vps.tags?.length ? <div className="mt-3 flex flex-wrap gap-2"><Tag size={15} className="mt-1 text-accent" />{vps.tags.map((tag) => <Badge key={tag} variant="outline">{tag}</Badge>)}</div> : null}{vps.notes ? <p className="mt-3 rounded-md bg-secondary/60 p-3 text-sm text-muted-foreground">{vps.notes}</p> : null}<form onSubmit={(event) => onProvision(vps, event)} autoComplete="off" className="mt-4 grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto]"><Label>Password một lần<Input type="password" maxLength={4096} autoComplete="new-password" placeholder="Install or rotate key" value={password} onChange={(event) => onPasswordChange(vps.id, event.target.value)} /></Label><Button type="submit" variant="secondary" disabled={busy} className="w-full self-end sm:w-auto"><KeyRound size={18} />Cài key</Button></form><div className="mt-3 grid gap-2 sm:grid-cols-2"><Button type="button" variant="secondary" disabled={busy} onClick={() => onVerify(vps)}><ShieldCheck size={18} />Kiểm tra key</Button><Button type="button" variant="destructive" disabled={busy} onClick={() => onDelete(vps)}><Trash2 size={18} />Xóa</Button></div></article>;
}

export function JobsPanel({ jobs, compact = false }: { jobs: DashboardOverview["jobs"]; compact?: boolean }) {
  const running = jobs.filter((job) => job.status === "running").length;
  const failed = jobs.filter((job) => job.status === "failed").length;
  const queued = jobs.filter((job) => job.status === "queued").length;
  return <Card className="min-w-0 max-w-full overflow-hidden border-slate-200"><CardHeader className="min-w-0 p-4 pb-3 sm:p-5 sm:pb-4"><div className="flex items-center justify-between gap-3"><CardTitle className="truncate text-xl font-black">{compact ? "Recent jobs" : "Jobs"}</CardTitle><Button type="button" variant="outline" size="sm" className="shrink-0 rounded-xl text-sm font-black">Logs</Button></div></CardHeader><CardContent className="grid min-w-0 max-w-full gap-3 overflow-hidden p-4 pt-0 sm:p-5 sm:pt-0">{jobs.length ? jobs.map((job) => { const progress = Math.min(100, Math.max(0, job.progress)); const durationText = job.durationMs != null ? `${(job.durationMs / 1000).toFixed(0)}s` : "Duration n/a"; const workerText = job.workerId || "Worker n/a"; return <article key={job.id} className="grid min-w-0 max-w-full gap-2 overflow-hidden rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><strong className="block min-w-0 max-w-full truncate text-[17px] font-black leading-6 text-slate-950" title={job.type}>{job.type}</strong><p className="mt-1 min-w-0 max-w-full truncate text-[15px] font-semibold leading-6 text-slate-500" title={`${job.vpsId} · ${job.progress}% progress`}><span className="sr-only">{job.vpsId} · {progress}% progress</span>{job.vpsId} · {workerText} · {progress}% progress</p></div><Badge className="shrink-0 uppercase" variant={chipVariant(job.status)}>{job.status}</Badge></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-cyan-600" style={{ width: `${progress}%` }} /></div><div className="flex flex-wrap items-center justify-between gap-2 text-[13px] font-bold leading-5 text-slate-500"><span>{durationText}</span>{job.errorLogUrl ? <a href={job.errorLogUrl} target="_blank" rel="noopener noreferrer" className="font-black text-primary underline-offset-4 hover:underline">View log</a> : <button type="button" disabled className="font-black text-slate-400">View log</button>}</div>{!compact && job.outputPreview ? <p className="line-clamp-1 min-w-0 max-w-full truncate text-sm font-medium text-muted-foreground" title={job.outputPreview}>{job.outputPreview}</p> : null}</article>; }) : <EmptyState>No jobs yet.</EmptyState>}<div className="grid gap-2 rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm font-bold leading-6 text-slate-600 sm:grid-cols-4"><span>Workers: {Math.max(1, jobs.length)}</span><span>Running: {running}</span><span>Queued: {queued}</span><span className={failed ? "rounded-lg bg-red-600 px-2 py-1 font-black text-white" : "text-emerald-700"}>Failed: {failed}</span>{failed ? <span className="w-fit rounded-lg bg-red-50 px-2 py-1 font-black text-red-700 ring-1 ring-red-200">Errors logged</span> : null}<span className="sm:col-span-4">Auto-refresh follows dashboard refresh. Passwords are never stored.</span></div></CardContent></Card>;
}
export function MetricsPanel({ metrics }: { metrics: DashboardOverview["metrics"] }) {
  return <Card><CardHeader><CardTitle>Metrics</CardTitle><CardDescription>Telemetry freshness and resource usage.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{metrics.length ? metrics.map((metric) => <article key={metric.vpsId} className="rounded-lg border border-border bg-secondary/50 p-4"><div className="flex items-center justify-between gap-3"><strong>{metric.vpsId}</strong><Badge variant={chipVariant(metric.freshness)}>{metric.freshness}</Badge></div><p className="mt-2 text-sm text-muted-foreground">CPU {metric.cpu}% · Memory {metric.memory}% · Disk {metric.disk}%</p><p className="mt-1 text-xs font-black uppercase tracking-[0.14em] text-accent">Collected {freshnessLabel(metric.collectedAt)}</p></article>) : <EmptyState>No metrics yet.</EmptyState>}</CardContent></Card>;
}

export function AuditPanel({ events, compact = false }: { events: DashboardOverview["auditEvents"]; compact?: boolean }) {
  return <Card className="min-w-0 max-w-full overflow-hidden border-slate-200"><CardHeader className="min-w-0 p-4 pb-3 sm:p-5 sm:pb-4"><CardTitle className="truncate text-xl font-black">{compact ? "Recent audit" : "Audit"}</CardTitle></CardHeader><CardContent className="min-w-0 max-w-full overflow-hidden p-4 pt-0 sm:p-5 sm:pt-0">{events.length ? <div className="min-w-0 overflow-hidden rounded-xl border border-slate-200"><div className="hidden grid-cols-[1.05fr_1.35fr_0.9fr_1fr_0.85fr_0.8fr_0.7fr] gap-3 bg-slate-100 px-3 py-2 text-[12px] font-black uppercase tracking-[0.08em] text-slate-500 md:grid"><span>Time</span><span>Event</span><span>Actor</span><span>Server</span><span>Severity</span><span>Status</span><span>Action</span></div><div className="divide-y divide-slate-200">{events.map((event, index) => { const target = event.serverLabel || [event.resourceType, event.resourceId].filter(Boolean).join("/") || "dashboard"; const severity = event.severity || (event.result === "success" ? "info" : "warning"); const eventLabel = event.actionLabel || event.action; return <article key={event.id} className={`grid min-w-0 gap-2 p-3 text-sm font-semibold leading-6 text-slate-600 transition hover:bg-cyan-50/60 md:grid-cols-[1.05fr_1.35fr_0.9fr_1fr_0.85fr_0.8fr_0.7fr] md:items-center ${index % 2 ? "bg-slate-50/60" : "bg-white"}`}><span className="truncate font-bold text-slate-600">{formatDate(event.timestamp)}</span><span className="flex min-w-0 items-center gap-2 font-mono text-[15px] font-semibold text-slate-950"><Activity className="shrink-0 text-slate-500" size={16} /><span className="truncate" title={event.action}>{eventLabel}</span></span><span className="truncate">{event.actor || "system"}</span><span className="w-fit max-w-full truncate rounded-full border border-slate-200 bg-white px-2 py-1 text-xs font-black text-slate-600" title={target}>{target}</span><Badge className="w-fit uppercase" variant={severity === "warning" ? "warning" : severity === "critical" ? "destructive" : "outline"}>{severity}</Badge><Badge className="w-fit uppercase" variant={chipVariant(event.result)}>{event.result}</Badge><button type="button" className="w-fit font-black text-primary underline-offset-4 hover:underline">Details</button></article>; })}</div></div> : <EmptyState>No audit events yet.</EmptyState>}</CardContent></Card>;
}
export function TerminalPanel({ terminal }: { terminal: DashboardOverview["terminal"] }) {
  return <Card className="min-w-0"><CardHeader><CardTitle>{terminal.label}</CardTitle><CardDescription>Canned output only. No real SSH connections.</CardDescription></CardHeader><CardContent className="space-y-3"><div className="flex items-center gap-2 font-black"><TerminalSquare size={18} />No real SSH connections</div><p className="text-sm text-muted-foreground">Commands: {terminal.commands.join(", ") || "none"}</p>{terminal.sessions.map((session) => <pre key={session.command} className="max-w-full overflow-x-auto whitespace-pre-wrap break-words rounded-md bg-primary p-3 text-sm text-primary-foreground">$ {session.command}{"\n"}{session.output}</pre>)}</CardContent></Card>;
}

export function SettingsPanel({ overview }: { overview: DashboardOverview }) {
  return <Card><CardHeader><CardTitle>Settings</CardTitle><CardDescription>Read-only safety posture.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Badge variant="outline">APP_MODE={overview.settings.appMode}</Badge><Badge variant="outline">web terminal {overview.settings.webTerminalEnabled ? "enabled" : "disabled"}</Badge><Badge variant="outline">real SSH {overview.settings.realSshEnabled ? "enabled" : "disabled"}</Badge><Badge variant="outline">local auth {overview.settings.authRequiredInLocalMode ? "required" : "off"}</Badge></CardContent></Card>;
}

function EmptyState({ children }: { children: ReactNode }) {
  return <div className="rounded-md border border-dashed border-border p-6 text-center text-sm text-muted-foreground">{children}</div>;
}
