export type AuditEvent = {
  id: string;
  actor: string;
  action: string;
  resourceType: string;
  resourceId?: string;
  result: "success" | "failure" | "blocked";
  timestamp: string;
  metadata?: Record<string, unknown>;
  severity?: "info" | "warning" | "critical";
  serverLabel?: string;
  actionLabel?: string;
  eventCode?: string;
  sourceIp?: string;
  requestId?: string;
  client?: string;
  jobId?: string;
  durationMs?: number;
  authMethod?: string;
  reason?: string;
};
