import { EventEmitter } from "node:events";
import { describe, expect, it, vi } from "vitest";
import { parseTerminalMessage } from "../src/terminal/terminal-protocol.js";
import { TerminalSessionService, type TerminalSocket } from "../src/terminal/terminal-session.service.js";

describe("terminal flow-control safety", () => {
  it("rejects oversized input with stable protocol error", () => {
    expect(() => parseTerminalMessage(JSON.stringify({ type: "input", data: "x".repeat(64 * 1024 + 1) }))).toThrow("PROTOCOL_ERROR");
  });
  it("does not expose payloads in protocol errors", () => {
    expect(() => parseTerminalMessage("not-json")).toThrow("PROTOCOL_ERROR");
  });
});

class Socket implements TerminalSocket { messages:string[]=[]; closes:any[]=[]; bufferedAmount=0; message?:any; drain?:any; errored?:any; deferred: Array<(error?: Error)=>void> = []; deferCallbacks=false; send=(x:string, callback?: (error?: Error)=>void)=>{ this.messages.push(x); if (callback && this.deferCallbacks) this.deferred.push(callback); else callback?.(); }; close=(...x:any[])=>this.closes.push(x); onMessage=(h:any)=>this.message=h; onClose=()=>{}; onError=(h:any)=>this.errored=h; onDrain=(h:any)=>this.drain=h; receive(v:unknown){this.message(JSON.stringify(v));} completeNext(error?: Error){this.deferred.shift()?.(error);} completeAll(){while(this.deferred.length)this.completeNext();} }
function flow(outputBufferBytes=8,inputBufferBytes=8) { const channel:any=new EventEmitter(); channel.pause=vi.fn(); channel.resume=vi.fn(); channel.end=vi.fn(); channel.setWindow=vi.fn(); channel.write=vi.fn(()=>true); const shell={channel,client:{end:vi.fn()},close:vi.fn()}; const socket=new Socket(); const cfg:any={enableWebTerminal:true,mode:"local",terminal:{global:10,perDashboard:3,perVps:2,openTimeoutMs:100,idleTimeoutMs:1000,lifetimeMs:2000,revocationPollMs:500,heartbeatMs:100,outputBufferBytes,inputBufferBytes,slowConsumerTimeoutMs:20}}; const service=new TerminalSessionService(cfg,{get:vi.fn(async()=>({id:"v",kind:"remote"}))} as any,{readPrivateKey:vi.fn(async()=>"KEY")} as any,{openManagedShell:vi.fn(async()=>shell)} as any,{authenticateById:vi.fn(async()=>({id:"d",expiresAt:new Date(Date.now()+60_000).toISOString()}))} as any); return {channel,shell,socket,service}; }
const opening={type:"open",version:1,vpsId:"v",cols:80,rows:24} as const;
describe("terminal bridge flow control",()=>{
  it("pauses bounded output then resumes and flushes on socket drain",async()=>{ /* Arrange */ vi.useFakeTimers(); const x=flow(); x.socket.bufferedAmount=9; await x.service.open(x.socket,"d",opening); /* Act */ x.channel.emit("data",Buffer.from("12345678")); /* Assert positive */ expect(x.channel.pause).toHaveBeenCalledOnce(); expect(x.socket.messages.map(value => JSON.parse(value)).filter((m:any)=>m.type==="output")).toHaveLength(0); x.socket.bufferedAmount=0; await vi.advanceTimersByTimeAsync(10); expect(x.channel.resume).toHaveBeenCalledOnce(); expect(x.socket.messages.map(value => JSON.parse(value)).find((m:any)=>m.type==="output")?.data).toBe("12345678"); await x.service.onApplicationShutdown(); vi.useRealTimers(); });
  it("closes a slow consumer instead of exceeding the output bound",async()=>{ /* Arrange */ vi.useFakeTimers(); const x=flow(8); x.socket.bufferedAmount=9; await x.service.open(x.socket,"d",opening); /* Act */ x.channel.emit("data",Buffer.from("12345678")); await vi.advanceTimersByTimeAsync(201); /* Assert negative */ expect(x.socket.closes[0]?.[1]).toBe("slow_consumer"); vi.useRealTimers(); });
  it("queues input after write=false, flushes in order on SSH drain, and overflows safely",async()=>{ /* Arrange */ const x=flow(8,5); x.channel.write.mockReturnValueOnce(false).mockReturnValue(true); await x.service.open(x.socket,"d",opening); /* Act/Assert positive */ x.socket.receive({type:"input",data:"ab"}); x.socket.receive({type:"input",data:"cd"}); expect(x.channel.write).toHaveBeenCalledTimes(1); x.channel.emit("drain"); expect(x.channel.write.mock.calls.map((c:any[])=>c[0])).toEqual(["ab","cd"]); /* Negative */ const y=flow(8,3); y.channel.write.mockReturnValue(false); await y.service.open(y.socket,"d",opening); y.socket.receive({type:"input",data:"ab"}); y.socket.receive({type:"input",data:"cdef"}); await Promise.resolve(); expect(y.socket.closes[0]?.[1]).toBe("input_overflow"); });
  it("delivers many small output chunks through send callbacks without poll delay", async () => { vi.useFakeTimers(); const x = flow(128); await x.service.open(x.socket, "d", opening); for (let i = 0; i < 32; i++) x.channel.emit("data", Buffer.from(`c${i}`)); const outputs = x.socket.messages.map(v => JSON.parse(v)).filter((m: any) => m.type === "output"); expect(outputs.map((m: any) => m.data)).toEqual(Array.from({ length: 32 }, (_, i) => `c${i}`)); expect(x.socket.closes).toHaveLength(0); await x.service.onApplicationShutdown(); vi.useRealTimers(); });
  it("emits split UTF-8 exactly once", async () => { const x = flow(32); await x.service.open(x.socket, "d", opening); const bytes = Buffer.from("€"); x.channel.emit("data", bytes.subarray(0, 1)); x.channel.emit("data", bytes.subarray(1)); const outputs = x.socket.messages.map(v => JSON.parse(v)).filter((m: any) => m.type === "output"); expect(outputs.map((m: any) => m.data)).toEqual(["€"]); expect(JSON.stringify(outputs)).not.toContain("�"); await x.service.onApplicationShutdown(); });
  it("resumes at most once per pause cycle after progress", async () => { vi.useFakeTimers(); const x = flow(8); x.socket.bufferedAmount = 9; await x.service.open(x.socket, "d", opening); x.channel.emit("data", Buffer.from("12345678")); expect(x.channel.pause).toHaveBeenCalledTimes(1); x.socket.bufferedAmount = 0; await vi.advanceTimersByTimeAsync(10); expect(x.channel.resume).toHaveBeenCalledTimes(1); await x.service.onApplicationShutdown(); vi.useRealTimers(); });
  it("drains deferred output before closed on channel close", async () => { const x=flow(128); x.socket.deferCallbacks=true; await x.service.open(x.socket,"d",opening); x.channel.emit("data",Buffer.from("one")); x.channel.emit("data",Buffer.from("two")); x.channel.emit("close"); expect(x.socket.closes).toHaveLength(0); x.socket.completeAll(); await Promise.resolve(); expect(x.socket.messages.map(v=>JSON.parse(v).type)).toEqual(["ready","output","output","closed"]); expect(x.socket.closes).toHaveLength(1); });
  it("uses bounded timeout for blocked channel close", async () => { vi.useFakeTimers(); const x=flow(8); x.socket.bufferedAmount=9; await x.service.open(x.socket,"d",opening); x.channel.emit("data",Buffer.from("blocked")); x.channel.emit("close"); await vi.advanceTimersByTimeAsync(19); expect(x.socket.closes).toHaveLength(0); await vi.advanceTimersByTimeAsync(1); expect(x.socket.closes).toHaveLength(1); vi.useRealTimers(); });
  it("orders split decoder tail before closed", async () => { const x=flow(32); x.socket.deferCallbacks=true; await x.service.open(x.socket,"d",opening); const b=Buffer.from("€"); x.channel.emit("data",b.subarray(0,2)); x.channel.emit("data",b.subarray(2)); x.channel.emit("close"); x.socket.completeAll(); await Promise.resolve(); const m=x.socket.messages.map(v=>JSON.parse(v)); expect(m.filter((v:any)=>v.type==="output").map((v:any)=>v.data)).toEqual(["€"]); expect(m.at(-1)?.type).toBe("closed"); });
  it("ignores late callbacks after unrelated cleanup", async () => { const x=flow(32); x.socket.deferCallbacks=true; await x.service.open(x.socket,"d",opening); x.channel.emit("data",Buffer.from("late")); x.socket.errored?.(); await Promise.resolve(); const n=x.socket.messages.length; x.socket.completeAll(); await Promise.resolve(); expect(x.socket.messages.length).toBe(n); expect(x.socket.closes).toHaveLength(1); });
  it("handles synchronous callbacks once and orders closed last", async () => { const x=flow(64); await x.service.open(x.socket,"d",opening); x.channel.emit("data",Buffer.from("a")); x.channel.emit("data",Buffer.from("b")); x.channel.emit("close"); await Promise.resolve(); const m=x.socket.messages.map(v=>JSON.parse(v)); expect(m.filter((v:any)=>v.type==="output").map((v:any)=>v.data)).toEqual(["a","b"]); expect(m.at(-1)?.type).toBe("closed"); });
});
